### ISSUE TITLE
Enrich Type of ID's for SQL AST

### ISSUE THREAD

**Issue by lag47** [hgoldstein95/CIS670-project#1]
Current the `Ident` type simply aliases strings. However, in SQL, identifiers not only contain column names, but also table names, i.e.
```
Select f2 from T1, T2 where T1.f1 = T2.f1
```
The following may be a better type for identifiers
```
type Ident = (Option Table) * String;
```

**Comment by hgoldstein95** [comment]
Closed by #2.
